### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by wmertens** [bencevans/sonos-cli#45]
```
$ sonos-cli --zone 'Dining Room' volume
ERROR: callback is not a function
```

no stack trace :-(

```
$ pnpm ls sonos
bin@1.0.0 /Users/wmertens/bin
└─┬ sonos-cli@0.5.2
  └── sonos@1.12.2
```

**Comment by bencevans** [comment]
Thanks for the report. I don't currently have access to my Sonos system but have pushed an update so the stack trace will print. Would you mind `npm i -g sonos-cli@latest` and running again or maybe even submit a pull-request with a fix?
