### ISSUE TITLE
sonos if_playing doesn't works with grouped equipments

### ISSUE THREAD

**Issue by pzim-devdata** [bencevans/sonos-cli#59]
Hello, thank you very much for sonos-cli, it's really great :-)

I have found a little problem with `sonos if_playing` command with grouped devices.

When I group sonos's devices together and when I execute this command : 
`sonos connect group one : roam group one : roam_2 group one : roam_3 group one`
`sonos one if_playing volume 20 : connect if_playing rel_vol -6 : roam if_playing volume 13 : roam_2 vol 10 : roam_3 rel_vol 6`
Only the volume of sonos one, roam_2 and roam_3 change

So it's only changing the volume of the coordinator `one` with `ìf_playing`

**Comment by bencevans** [comment]
Hi @pzim-devdata. We don’t have that command in this project. I think you might be running https://github.com/avantrec/soco-cli

**Comment by pzim-devdata** [comment]
I'm so confused, sorry. I will remove this

**Comment by pzim-devdata** [comment]
@bencevans bencevans Sorry I can't delete the issue because I'm not the owner.
[Deleting an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue)
