### ISSUE TITLE
Url of a Sonos favourite.

### ISSUE THREAD

**Issue by kimaldis** [bencevans/sonos-cli#9]
I'm trying to figure out how to get the url of a Sonos favourite so I can pass it to play. Any thoughts?

thanks

**Comment by bencevans** [comment]
Hi @kimaldis!

I've just added the track URI to the `sonos current-track` command output. Play your track and run the command. You can also get it programmatically using the [node-sonos](https://github.com/bencevans/node-sonos) module by calling `device.currentTrack()`.

**Comment by bencevans** [comment]
Make sure you update the cli first... `npm install --global sonos-cli` should do the trick.
